In [1]:
import openturns as ot
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [ ]:
a = np.array([1, 2, 3.5])

In [ ]:
dim = 2
n_sample = 4
n_realization = 3

a np.eyes((2,2))
print(a)

a = np.zeros((dim, n_sample, n_realization))
a[:,: ,1] = 2
a[1,:,:] = 3
a

In [ ]:
a[1]

In [31]:
Ni = 4
a = np.random.randint(0, Ni, size=(Ni,3))
print(a)
a.mean(axis=0)


[[1 1 0]
 [2 3 3]
 [1 2 3]
 [1 0 2]]


array([ 1.25,  1.5 ,  2.  ])

In [ ]:
Nv = 4
n_boot_var = 10
np.random.randint(0, Nv, size=(Nv, n_boot_var))

In [ ]:
class Voiture(object):

    def __init__(self,nb):
        self.roues = nb

    @property
    def roues(self):
        print "Récupération du nombre de roues"
        return self._roues

    @roues.setter
    def roues(self, v):
        print "Changement du nombre de roues"
        self._roues  =  v

In [ ]:
ma_voiture=Voiture(5)
#ma_voiture.roues = 5

In [ ]:
import openturns as ot
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

from shapley import ShapleyIndices, ShapleyKrigingIndices
from shapley.tests import Ishigami, AdditiveGaussian
from shapley.plots import set_style_paper, plot_sensitivity_results

%load_ext autoreload
%autoreload 2

%matplotlib inline

set_style_paper()

savefigs = True
ylim = [-0.05, 1.05]

## The model

In [ ]:
dim = 2
beta = None
model = AdditiveGaussian(dim=dim, beta=beta)
theta = [0.3]
model.copula_parameters = theta
model.shapley_indices = [1./dim]*dim
if dim == 2 and beta is None:
    output_var = dim*( 1 + sum(theta))
    model.first_order_sobol_indices = [(1 + 2*theta[0] + theta[0]**2)/output_var]*dim
    model.total_sobol_indices = [(1.- theta[0]**2)/output_var]*dim

## Sobol indices with a classical Monte-Carlo sampling

In [ ]:
ot.RandomGenerator.SetSeed(0)
np.random.seed(0)
Nv = 500
No = 50
Ni = 25

# Evaluate the model
shapley = ShapleyIndices(model.input_distribution)
shapley.build_mc_sample(model=model, n_perms=None, Nv=Nv, No=No, Ni=Ni)

In [ ]:
n_boot_var = 30
n_boot_No = 30
n_boot_Ni = 30
shapley_results = shapley.compute_indices(n_boot_var=n_boot_var, 
                                         n_boot_No=n_boot_No,
                                         n_boot_Ni=n_boot_Ni)